version: '3.9'

services:
    mysqldb:
     container_name: 'mysqldb'
       image: mysql:8
      restart: unless-stopped
      environnement:
      MYSQL_ROOT_PASSWORD: admin
       volumes:                                                                       
          - /home/mysqldata:/var/lib/mysql
    spring_app:
      container_name: tpachat
        image: tpachat
          restart: on_failure
            port: 
              -9090:9090
                  depends_on:
                     -mysqldb