# version: '3.9'
# services:
#   mysqldb:
#           container_name: mysqldb
#           image: mysql:8
#           restart: unless-stopped
#           volumes:
#                 - /home/mysqldata:/var/lib/mysql
#           environnement:
#                 MYSQL_ROOT_PASSWORD: admin

#   spring_app:
#           container_name: tpachat
#           image: tpachat
#           restart: on_failure
#           port:
#                 - 9090:9090
#           depends_on:
#                   - mysqldb
version: '3.9'
services:
  mysqldb:
          container_name: mysqldb
          image: mysql:8
          #environnement:
                #MYSQL_ROOT_PASSWORD: admin
          ports:
                - 3306:3306
                  # restart: unless-stopped
          volumes:
                - /home/mysqldata:/var/lib/mysql


  spring_app:
          image: tpachat
          container_name: tpachat
          restart: on_failure
          ports:
                - 9090:9090
          depends_on:
                - mysqldb